### ISSUE TITLE
login and store token

### ISSUE THREAD

**Issue by IronYoo** [yoo-myeong/carCamping-service#5]
1. 백엔드에서 name과 token받으면 token은 localstorage에 저장
2. localstorage에서 token가져와서 값이 있으면 백엔드요청시에 헤더에 추가해주는 미들웨어 생성
3. token을 보내야 하는 요청에 미들웨어 추가

**Comment by yoo-myeong** [comment]
+ 로그인 버튼이 눌리면 /login으로 POST 요청
+ POST /auth/login에서는 백엔드 서버의 /auth/login으로 post요청
+ 응답받은 데이터의 상태코드가 401이면 다시 로그인페이지로 가서 입력정보가 잘못됐음을 알림
+ 그렇지 않으면 로그인 성공으로 판단하고 sessionStorage 저장을 위해 전달받은 {토큰, 이름} json을 setSessionStorage.ejs로 전달
+ setSessionStorage.ejs에서 숨겨진 p태그에 토큰값을 넣고 다시 javascript로 세션스토리지에 토큰을 저장한 뒤 메인페이지로 이동
+ 모든 페이지는 navbar템플릿을 시작부분에, authCertification 템플릿을 끝 부분 script태그 위에 상속받음
    - authCertification.html은 백엔드 서버의 세션스토리지에서 토큰을 꺼내온 뒤 백엔드 서버의 me API로 인증 요청
    - 응답받은 상태코드가 401이면 로그인 버튼을 숨김 해제하고, 로그아웃 버튼과 유저네임은 숨김
    - 그렇지 않으면 토근이 유효하다고 판단하고 로그인을 숨기고, 로그아웃과 유저네임은 숨김 해제

**Comment by IronYoo** [comment]
일단 구현했지만 매우 불안정해서 다시 수정.
특히 setSessionStorage.ejs로 이동해서 세션을 저장하는 방식과 authCertification.html을 상속받아서 navbar를 조작하는 부분 이상함.

+ JS, CSS 파일 분리해서 각각 폴더에 카테고리에 맞는 이름으로 저장
+ login페이지에서 login을 누를 때
    - 모두 기입이 되어있는 지 확인
    - input의 기입된 내용을 object로 만들어서 body에 저장
    - fetch로 백엔드 서버의 loginAPI로 body와 함께 post 요청
    - 응답 코드가 401이면 unvalidAlert 숨김해제
    - 그렇지 않으면 sessionStorage에 토큰 저장하고 메인페이지로 이동
+ signup 페이지도 login과 같은 프로세스로 동작. 단, 정상응답코드를 받으면 메인페이지가 아니라 로그인 페이지로 이동
+ 메인 페이지에서 세션에 토큰이 저장되어 있다면
    - 백엔드 meAPI에 토큰 인증 요청을 보냄
    - 오류 응답코드를 받으면 토큰 삭제
    - 정상 응답코드를 받으면 로그인버튼 숨김, 로그아웃버튼과 username p태크 숨김해제
